In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset

# サンプルデータセット (ここではランダムなデータを使用)
class RandomDataset(Dataset):
  def __init__(self, length):
    self.length = length
    self.data = torch.randn(length, 10)  # 入力データ (10次元)
    self.targets = torch.randint(0, 2, (length,))  # ラベル (0 or 1)

  def __len__(self):
    return self.length

  def __getitem__(self, idx):
    return self.data[idx], self.targets[idx]

# 単純なニューラルネットワーク
class SimpleNN(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(10, 5)  # 入力層 (10次元) -> 隠れ層 (5次元)
    self.fc2 = nn.Linear(5, 1)   # 隠れ層 (5次元) -> 出力層 (1次元)
    self.sigmoid = nn.Sigmoid()  # シグモイド関数 (2値分類用)

  def forward(self, x):
    x = torch.relu(self.fc1(x))  # ReLU活性化関数
    x = self.fc2(x)
    x = self.sigmoid(x)
    return x

# データセット、データローダーの作成
dataset = RandomDataset(100)  # 100個のサンプルデータ
dataloader = DataLoader(dataset, batch_size=10, shuffle=True)  # バッチサイズ10

# モデル、損失関数、オプティマイザーの定義
model = SimpleNN()
criterion = nn.BCELoss()  # 2値分類の損失関数 (Binary Cross Entropy)
optimizer = optim.SGD(model.parameters(), lr=0.01)  # 確率的勾配降下法 (SGD)

# 学習ループ
num_epochs = 5
for epoch in range(num_epochs):
  for inputs, labels in dataloader:
    optimizer.zero_grad()  # 勾配の初期化
    outputs = model(inputs)  # 順伝播
    loss = criterion(outputs.squeeze(), labels.float())  # 損失の計算
    loss.backward()  # 逆伝播 (勾配の計算)
    optimizer.step()  # パラメータの更新

    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}")


Epoch [1/5], Loss: 0.6392
Epoch [1/5], Loss: 0.7021
Epoch [1/5], Loss: 0.7213
Epoch [1/5], Loss: 0.7030
Epoch [1/5], Loss: 0.5810
Epoch [1/5], Loss: 0.6814
Epoch [1/5], Loss: 0.6194
Epoch [1/5], Loss: 0.7327
Epoch [1/5], Loss: 0.6152
Epoch [1/5], Loss: 0.6504
Epoch [2/5], Loss: 0.6640
Epoch [2/5], Loss: 0.6473
Epoch [2/5], Loss: 0.6155
Epoch [2/5], Loss: 0.6676
Epoch [2/5], Loss: 0.6873
Epoch [2/5], Loss: 0.6707
Epoch [2/5], Loss: 0.6297
Epoch [2/5], Loss: 0.6777
Epoch [2/5], Loss: 0.7629
Epoch [2/5], Loss: 0.6166
Epoch [3/5], Loss: 0.5680
Epoch [3/5], Loss: 0.7050
Epoch [3/5], Loss: 0.7256
Epoch [3/5], Loss: 0.5731
Epoch [3/5], Loss: 0.6709
Epoch [3/5], Loss: 0.7599
Epoch [3/5], Loss: 0.6216
Epoch [3/5], Loss: 0.7369
Epoch [3/5], Loss: 0.6151
Epoch [3/5], Loss: 0.6585
Epoch [4/5], Loss: 0.6214
Epoch [4/5], Loss: 0.6964
Epoch [4/5], Loss: 0.5912
Epoch [4/5], Loss: 0.7168
Epoch [4/5], Loss: 0.6178
Epoch [4/5], Loss: 0.7322
Epoch [4/5], Loss: 0.6281
Epoch [4/5], Loss: 0.7592
Epoch [4/5],

In [3]:
# サンプルデータセット (ここではランダムなデータを使用)
class RandomDataset(Dataset):
  def __init__(self, length):
    self.length = length
    self.data = torch.randn(length, 10)  # 入力データ (10次元)
    self.targets = torch.randint(0, 2, (length,))  # ラベル (0 or 1)

  def __len__(self):
    return self.length

  def __getitem__(self, idx):
    return self.data[idx], self.targets[idx]

In [13]:
dataset = RandomDataset(100)
X, y = dataset[0]
X

tensor([ 1.0154, -0.7223, -0.3501,  0.1600, -0.9460, -1.6584,  1.4541,  0.2858,
         1.1821,  0.3361])

In [14]:
dataloader = DataLoader(dataset, batch_size=10, shuffle=True)

In [15]:
for inputs, labels in dataloader:
  print(inputs)
  print(labels)
  break

tensor([[ 0.3293,  0.5235, -0.7247,  1.6076, -1.0546, -1.1495,  0.1805,  0.5477,
         -0.0256,  0.2789],
        [-1.0288, -1.7827, -0.0497, -1.2763, -0.1239, -0.3720, -1.1847,  1.3246,
         -0.3835,  0.0781],
        [-1.1395, -0.0538,  0.6418,  1.4607, -0.0650,  0.4627, -0.5758, -1.0084,
         -1.4050,  1.3970],
        [-0.2297, -0.9599, -1.5847,  1.3666, -0.0836, -0.6195,  0.7608, -0.2206,
         -1.1134,  1.6231],
        [-0.8524,  0.0851, -1.1628,  0.0283,  1.9620, -0.0841,  0.3384, -1.3309,
          1.1852,  0.9140],
        [-0.7126, -0.1463,  0.7158, -0.0118,  1.0873,  0.4211, -0.3810, -0.4288,
         -0.7115,  1.8796],
        [-1.0565,  0.3741,  2.1807, -0.3285,  0.8070,  0.2312, -0.1483,  0.0325,
         -1.6218, -1.8513],
        [-0.1956,  0.3662,  0.1584, -0.0749,  0.3517, -0.3533, -2.2447, -0.9180,
          0.7452, -1.9275],
        [ 0.5235, -0.9579,  0.6159, -0.6936,  0.2763, -0.7786,  0.4613, -0.5170,
         -0.3087, -0.3709],
        [-1.9946,  

In [11]:
from torch.utils.data import random_split
train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size
train_dataset, test_dataset = random_split(dataset, [train_size, test_size])

In [12]:
train_dataloader = DataLoader(train_dataset, batch_size=10, shuffle=True)
test_dataloader = DataLoader(test_dataset, batch_size=10, shuffle=False)

In [18]:
for inputs, labels in train_dataloader:
  print(inputs)
  print(labels)
  break

tensor([[-0.4548, -1.2205, -1.0151, -0.8685,  0.7533,  0.0575, -0.6123,  0.9436,
         -1.4239, -1.1502],
        [ 0.0329, -1.1848,  0.3009,  1.3876, -1.2279, -0.2404,  1.1148,  0.6754,
          0.0048, -0.8577],
        [ 0.7657, -0.1015, -1.5893,  1.1822,  0.4624,  1.9341, -0.9013,  3.9917,
          0.5014,  0.0730],
        [-0.1712, -1.4664,  0.9519, -0.4785,  0.3289,  0.5395,  1.6412, -1.6922,
          0.7201,  1.0498],
        [-1.5620, -1.5531,  0.0280,  0.2431,  1.8253, -0.4210,  0.1713, -0.6595,
          0.2650, -0.9849],
        [ 0.9731,  0.1491,  0.1544,  0.2604,  1.7433,  0.8198, -1.2277, -0.4566,
         -0.9544, -0.5165],
        [ 0.1809,  0.7922,  1.1614, -1.6620,  0.4246,  0.1799,  0.4626, -1.4174,
          2.1825, -0.2727],
        [ 1.6497,  0.3646, -1.5447, -1.3083, -1.4818,  0.1548,  1.4457,  0.1484,
         -0.1990, -1.0319],
        [-0.7032, -1.4864,  1.7270, -0.0276,  0.9989,  1.0395, -0.0106,  3.3457,
          1.4093, -0.0826],
        [ 0.6926,  

In [19]:
class SimpleNN(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(10, 5)  # 入力層 (10次元) -> 隠れ層 (5次元)
    self.fc2 = nn.Linear(5, 1)   # 隠れ層 (5次元) -> 出力層 (1次元)
    self.sigmoid = nn.Sigmoid()  # シグモイド関数 (2値分類用)

  def forward(self, x):
    x = torch.relu(self.fc1(x))  # ReLU活性化関数
    x = self.fc2(x)
    x = self.sigmoid(x)
    return x

In [20]:
model = SimpleNN()
y = model(X)
y

tensor([[0.4722],
        [0.5880],
        [0.4722],
        [0.5311],
        [0.4918],
        [0.5969],
        [0.4748],
        [0.4745],
        [0.4762],
        [0.4774]], grad_fn=<SigmoidBackward0>)

In [23]:
dataset = RandomDataset(100)  # 100個のサンプルデータ
dataloader = DataLoader(dataset, batch_size=10, shuffle=True)  # バッチサイズ10

# モデル、損失関数、オプティマイザーの定義
model = SimpleNN()
criterion = nn.BCELoss()  # 2値分類の損失関数 (Binary Cross Entropy)
optimizer = optim.SGD(model.parameters(), lr=0.01)  # 確率的勾配降下法 (SGD)

# 学習ループ
num_epochs = 5
for epoch in range(num_epochs):
  for batch, (inputs, labels) in enumerate(dataloader):
    optimizer.zero_grad()
    outputs = model(inputs)
    loss = criterion(outputs.squeeze(), labels.float())
    loss.backward()
    optimizer.step()

    print(f"Epoch [{epoch+1}/{num_epochs}], Batch [{batch}/{len(dataloader)}], Loss: {loss.item():.4f}")


Epoch [1/5], Batch [0/10], Loss: 0.6941
Epoch [1/5], Batch [1/10], Loss: 0.6761
Epoch [1/5], Batch [2/10], Loss: 0.7319
Epoch [1/5], Batch [3/10], Loss: 0.7330
Epoch [1/5], Batch [4/10], Loss: 0.7151
Epoch [1/5], Batch [5/10], Loss: 0.6594
Epoch [1/5], Batch [6/10], Loss: 0.7181
Epoch [1/5], Batch [7/10], Loss: 0.6918
Epoch [1/5], Batch [8/10], Loss: 0.7448
Epoch [1/5], Batch [9/10], Loss: 0.7204
Epoch [2/5], Batch [0/10], Loss: 0.7219
Epoch [2/5], Batch [1/10], Loss: 0.6814
Epoch [2/5], Batch [2/10], Loss: 0.7338
Epoch [2/5], Batch [3/10], Loss: 0.7208
Epoch [2/5], Batch [4/10], Loss: 0.7055
Epoch [2/5], Batch [5/10], Loss: 0.6855
Epoch [2/5], Batch [6/10], Loss: 0.7375
Epoch [2/5], Batch [7/10], Loss: 0.6909
Epoch [2/5], Batch [8/10], Loss: 0.6906
Epoch [2/5], Batch [9/10], Loss: 0.7043
Epoch [3/5], Batch [0/10], Loss: 0.7019
Epoch [3/5], Batch [1/10], Loss: 0.6776
Epoch [3/5], Batch [2/10], Loss: 0.7417
Epoch [3/5], Batch [3/10], Loss: 0.7037
Epoch [3/5], Batch [4/10], Loss: 0.7326
